### ISSUE TITLE
hmac-sha1 for more than one letter

### ISSUE THREAD

**Issue by wpasieka** [massung/sha1#1]
I think there is a problem in here, if there is any chance You could fix it, please:

https://www.freeformatter.com/hmac-generator.html#ad-output

(hmac-sha1-hex "a" "a") "3902ed847ff28930b5f141abfa8b471681253673"
freeformater                     3902ed847ff28930b5f141abfa8b471681253673

 (hmac-sha1-hex "aa" "a") "2719d64ab2081c6deac6a5618733fafc510eead5"
freeformater                        d07e787df30226cb6110bf78e312a4195ce4c5c9

**Comment by massung** [comment]
@wpasieka thanks for the issue. Going to freeformatter, though, it produces the same output:

```
Copy-paste the string here:
a

Secret Key:
aa

Computed HMAC:
2719d64ab2081c6deac6a5618733fafc510eead5
```

I get your output (d07e787df30226cb6110bf78e312a4195ce4c5c9) if I swap the arguments. In the SHA1 library, the secret/salt is the first parameter and the string to hash is the second:

```
CL-USER> (sha1:hmac-sha1-hex "aa" "a")
"2719D64AB2081C6DEAC6A5618733FAFC510EEAD5"
```

Closing the issue, but if you think I've made an error elsewhere (e.g. the documentation), please open it up again and let me know. 😃

**Comment by wpasieka** [comment]
Your code is perfectly clear by stating:  'key and 'message. It is always good to analyze it first, rather than going into a brain freeformatter exercises on the website : ). 

And it is extremely concise, comparing to other crypto packages -   allowing to use it with an understanding.  Well done, thank You.

**Comment by wpasieka** [comment]
Hello Mr Massung : )

I am wondering if You are planning to write a simple hmac-sha256, similarly to sha1, which I hereby confirm works flawlessly + base64.

More and more API require sha256 - by using Your packages with sha1 I understand what  is going behind the scenes.

The sha256 is available in the ironclad, but it is a massive package, with many classes etc., trying to figure out how all together works is almost mission impossible.

Maybe You have got the hmac-sha256, but unpublished, yet ? :  )

**Comment by massung** [comment]
Interesting. I've never had a need. So, no, I don't have it sitting around unpublished, sadly. I certainly could take a look at it, though, and see if it's something I could whip together.

**Comment by wpasieka** [comment]
The time would not have been wasted, an example:

https://docs.paynow.pl/#section/Payments/Flow-of-statuses

"The signature is calculated on the basis of the request's body using the HMAC SHA256 algorithm with a secret key shared between Paynow and the Merchant. The output is additionally encoded in Base64."

There are companies like Stripe/ Plaid and so called PSD2  (Payment Services Directive) with the fintech companies replacing the banks.

So having it handy and published, could end up with some business in the future.

The Paynow gate works with the Ironclad -which loads 95% of things which will never be used, but extracting 10 defun for the sha256 it is a convoluted task....

Your hmac-sha1 is well written and convenient - so hopefully the hmac-sha256 will join the family :).

**Comment by wpasieka** [comment]
Hello Mr Massung,

I am wondering if You would consider developing the hmac-sh256 based on Your solutions, during this boring Covid-19 time, unless somehow You are more busy  :)

I wrote the whole code for the Paynow gate and we shall get connected Live next week, with using Ironclad which works, but it takes about 4-5 second to load the Ironclad itself.

And I want to make this Payment Gate available for a future clients, all in Lisp,  with a logging through the SSH to the REPL.

And keeping them waiting for 5 seconds is not the best selling point...

If all works smoothly we could expand our solution, and it opens up the space for a commercial co-operation with You in the future, it is not a promise, because You know how difficult it is to commercialize anything, but sometimes it happens.


Kind Regards,
Adrian
